apiVersion: apps/v1
kind: Deployment
metadata:
  name: everyone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: everyone
  template:
    metadata:
      labels:
        app: everyone
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: everyone
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ba10ec65-b64f-402e-82d8-8aad8bf3f81d"
        - name: Vless_Path
          value: "/vlfu855"
        - name: Vmess_UUID
          value: "ba10ec65-b64f-402e-82d8-8aad8bf3f81d"
        - name: Vmess_Path
          value: "/vmn966"
        - name: Share_Path
          value: "/v2link"
